version: "3.8"

networks:
  default:

# Uncomment configs if you want to change the entrypoint or patroni config
configs:
  haproxy.cfg:
    file: haproxy.cfg
  # patroni.yml:
  #   file: patroni.yml
  # entrypoint.sh:
  #   file: entrypoint.sh

# Uncomment volumes if you want persistence
volumes:
  dbdata:
    driver: local
  # dbdata1:
  #   driver: local
  # dbdata2:
  #   driver: local
  # dbdata3:
  #   driver: local
  etcddata1:
    driver: local
  etcddata2:
    driver: local
  etcddata3:
    driver: local

services:

  etcd1:
    image: 127.0.0.1:8889/bitnami/etcd:3.4.15
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
    - type: volume
      source: etcddata1
      target: /bitnami/etcd/data

  etcd2:
    image: 127.0.0.1:8889/bitnami/etcd:3.4.15
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
    - type: volume
      source: etcddata2
      target: /bitnami/etcd/data

  etcd3:
    image: 127.0.0.1:8889/bitnami/etcd:3.4.15
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
    - type: volume
      source: etcddata3
      target: /bitnami/etcd/data

  haproxy:
    image: haproxy:2.2.14-alpine
    configs:
    - source: haproxy.cfg
      target: /usr/local/etc/haproxy/haproxy.cfg
    ports:
    - "5002:5000" # Postgres
    - "7001:7000" # HAProxy stats

  db1:
    image: 127.0.0.1:8889/spgcontrols/patroni-postgres:2.0.2-13.3
    hostname: db1 # used for patroni name
    environment:
    - PATRONI_ETCD3_HOSTS='etcd1:2379','etcd2:2379','etcd3:2379'
    - PATRONI_admin_PASSWORD=SpgControls01!@
    - PATRONI_admin_OPTIONS=createrole,createdb
    #configs: &configs
    # - source: patroni.yml
    #   target: /app/patroni.yml
    # - source: entrypoint.sh
    #   target: /app/entrypoint.sh
    volumes:
    - type: volume
      source: dbdata
      target: /app/postgresql

  db2:
    image: 127.0.0.1:8889/spgcontrols/patroni-postgres:2.0.2-13.3
    hostname: db2 # used for patroni name
    environment:
    - PATRONI_ETCD3_HOSTS='etcd1:2379','etcd2:2379','etcd3:2379'
    - PATRONI_admin_PASSWORD=SpgControls01!@
    - PATRONI_admin_OPTIONS=createrole,createdb
    #configs: *configs
    volumes:
    - type: volume
      source: dbdata
      target: /app/postgresql

  db3:
    image: 127.0.0.1:8889/spgcontrols/patroni-postgres:2.0.2-13.3
    hostname: db3 # used for patroni name
    environment:
    - PATRONI_ETCD3_HOSTS='etcd1:2379','etcd2:2379','etcd3:2379'
    - PATRONI_admin_PASSWORD=SpgControls01!@
    - PATRONI_admin_OPTIONS=createrole,createdb
    #configs: *configs
    volumes:
    - type: volume
      source: dbdata
      target: /app/postgresql
